#151: 전체 사진 조회, 사진 추가 realm migration
depromeet/everyBody-iOS pull request #153
Opened 2022-03-13 15:26 UTC by anyukyung

## 🏋️‍♀️ PR 요약
전체 사진 조회, 사진 추가 realm migration......^-^....

#### 📌 변경 사항
변경사항 및 주의 사항 (모듈 설치 등)을 적어주세요.

##### 📸 ScreenShot

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue
close #151

2022-03-13 15:47 UTC, anyukyung commented on Noonbody/Noonbody/Source/Presentation/Home/Cells/ListCollectionViewCell.swift
> +//        }
떰네일. 가져오는거.. 호호 아직 구현을 안해서.. 주석 ^-^..

2022-03-13 15:47 UTC, anyukyung commented on Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
> +//        }
albumdata를 렘에서 가져오면서 요부분 에러가 떠서 주석처리

2022-03-13 15:47 UTC, anyukyung commented on Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
> +//        self.navigationController?.pushViewController(viewController, animated: true)
albumdata를 렘에서 가져오면서 요부분 에러가 떠서 주석처리

2022-03-14 09:07 UTC, yunyezl reviewed
일단은 DB 쪽만 봤어요~!
AlbumRepository 인터페이스에 대해 좀 더 생각해보면 좋을 것 같고
지금 우리가 sendFeedback 이란게 AlbumRepository 프로토콜에 없는데 DefaultAlbumRepository 내부에 구현되어있는 것 같더라고용.
이건 AlbumRepository에서가 아니라 별도로 분리해야할 것 같아요.
이따 더 자세히 말할게여~

2022-03-14 09:07 UTC, yunyezl commented on Noonbody/Noonbody/Source/Domain/Interfaces/Repositories/LocalAlbumRepository.swift
> +}
Album는 Local과 Server를 분리할 필요없이 하나만 있으면 되지 않을까요?

2022-03-14 09:07 UTC, yunyezl commented on Noonbody/Noonbody/Source/Data/Repositories/DefaultAlbumRepositry.swift
>  class DefaultAlbumRepositry: AlbumRepository {
DefaultAlbumRepository는 서버 DB에서 데이터를 가져오도록 구현된 AlbumRepository 프로토콜의 구현체였어요~!
이번에 Realm으로 마이그레이션 하면서, 데이터를 가져오는 DB가 서버 DB -> Realm DB로 바뀌게 될 거 잖아요?
그러면 네트워크 통신을 할 용도였던 DefaultAlbumRepository의 내부를 수정하는게 아니라, 
LocalAlbumRepository: AlbumRepository 형태로 AlbumRepsoitory 프로토콜을 채택한 새로운 구현체를 만들어서,
UseCase에서 DB를 가져오는 Repository를 DefaultAlbumRepository가 아닌 LocalAlbumRepository를 주입하도록 변경해야겠죱

2022-03-14 09:07 UTC, yunyezl commented on Noonbody/Noonbody/Source/Data/Repositories/DefaultAlbumRepositry.swift
> +        return Observable<Int>.create { observer -> Disposable in
이 부분은 이따 다시 얘기해봅시다~~
error를 throw 할 수 있도록 변경해야 할 것 같아요

2022-03-14 09:07 UTC, yunyezl commented on Noonbody/Noonbody/Source/Data/Repositories/DefaultPanoramaRepository.swift
>  class DefaultPanoramaRepository: PanoramaRepository {
이 부분도 마찬가지로 별도의 파일을 만들어주세요~

2022-03-14 09:07 UTC, yunyezl commented on Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
> +        print("Realm Database fileUrl: ", RealmManager.getUrl())
프린트문 해둔거 다 없애주시거나 debug일때만 뜨도록 해주세요

2022-03-18 12:34 UTC, yunyezl requested changes
흠..........
살짝 석연치않은 부분들이 좀 있지만. 그래도 훨신 나아졌다!!!! 
일단 1차 리뷰 완

2022-03-18 12:34 UTC, yunyezl commented on Noonbody/Noonbody/Source/Data/Realm/Model/LocalAlbum.swift
> +    @Persisted var albumDescription: String = "일 간의 기록"
요거 없애고 날짜 기준으로 뷰모델 혹은 유즈케이스에서 계산이용
-> 근데 뭔가 뷰모델 / 유즈케이스에서 하기 애매해서 여기 파일 내에서 엔티티도 매핑해줄 떄 바꿔도 ㄱㅊ을듯

2022-03-18 12:34 UTC, yunyezl commented on Noonbody/Noonbody/Source/Data/Realm/Repositories/LocalAlbumRepository.swift
> +        return observable
띠용? 아직 구현 못해서 네트워크 서비스 고대로 넣어둔건가요?

2022-03-18 12:34 UTC, yunyezl commented on Noonbody/Noonbody/Source/Domain/RepositoryProtocols/AlbumRepository.swift
> +    func sendFeedback(request: FeedbackRequestModel) -> Observable<Int>
당.장
구현 바로 못해도 따로 뺀 파일만 마ㅏㄴ들어놓으삼

2022-03-18 12:34 UTC, yunyezl commented on Noonbody/Noonbody/Source/Domain/RepositoryProtocols/AlbumRepository.swift
> +    func sendFeedback(request: FeedbackRequestModel) -> Observable<Int>
이거땜에 오류나지안ㄴ나요

2022-03-18 12:34 UTC, yunyezl commented on Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
> +    private let viewModel = AlbumViewModel(albumUseCase: DefaultFetchAlbumsUseCase(repository: LocalAlbumRepositry()), feedbackUseCase: DefaultAlbumUseCase(albumRepository: DefaultAlbumRepositry()))
이놈을..엊쩌면 좋지..빨리 코디네이터로 바끄던지 해야할듯

2022-03-18 12:34 UTC, yunyezl commented on Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
> +    private let viewModel = AlbumViewModel(albumUseCase: DefaultFetchAlbumsUseCase(repository: LocalAlbumRepositry()), feedbackUseCase: DefaultAlbumUseCase(albumRepository: DefaultAlbumRepositry()))
근데 Local로 다 만들어놓고 Default를 주입해놧으면.... 지금 네트워크 통신 버전으로 대고잇는거 아닌지?

2022-03-18 12:34 UTC, yunyezl commented on Noonbody/Noonbody/Source/Presentation/Home/ViewModels/AlbumViewModel.swift
> +    private let feedbackUseCase: AlbumUseCase
이름만 feedbackUseCase..?? 날 속이지마,

2022-03-18 13:09 UTC, anyukyung commented on Noonbody/Noonbody/Source/Presentation/Home/ViewModels/AlbumViewModel.swift
> +    private let feedbackUseCase: AlbumUseCase
@yunyezl  ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-03-18 13:09 UTC, anyukyung commented on Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
> +    private let viewModel = AlbumViewModel(albumUseCase: DefaultFetchAlbumsUseCase(repository: LocalAlbumRepositry()), feedbackUseCase: DefaultAlbumUseCase(albumRepository: DefaultAlbumRepositry()))
@yunyezl 마자요 똒똑아갓시

2022-03-18 14:35 UTC, yunyezl reviewed
마지맊.

2022-03-18 14:35 UTC, yunyezl commented on Noonbody/Noonbody/Source/Domain/UseCases/SendFeedbackUseCase.swift
> +    init(sendFeedbackRepository: DefaultSendFeedbackRepository) {
Type을 SendFeedbackRepository Protocol로 해주세영

2022-03-18 14:35 UTC, yunyezl commented on Noonbody/Noonbody/Source/Presentation/Home/ViewControllers/HomeViewController.swift
> +    private let viewModel = AlbumViewModel(albumUseCase: DefaultFetchAlbumsUseCase(repository: LocalAlbumRepositry()), feedbackUseCase: DefaultSendFeedbackUseCase(sendFeedbackRepository: DefaultSendF
이거 줄바꿈 한번 ㄲ

2022-03-18 14:35 UTC, yunyezl commented on Noonbody/Noonbody/Source/Data/Realm/Repositories/LocalAlbumRepository.swift
> +            let result = RealmManager.realm()?.objects(RMAlbums.self).first?.localAlbumArray
[RMAlbum] 안대나여

2022-03-18 14:44 UTC, yunyezl commented on Noonbody/Noonbody/Source/Presentation/Panorama/Cells/TopCollectionViewCell.swift
> +        panoramaImage.image = AlbumManager.loadImageFromDocumentDirectory(imageName: "\(albumId)/\(bodyPart)/\(imageName).png")
확장자 enum으로
enum 확장자: String {
     case jpeg
     case png
     case ~~
}
이런식으로 해놓고 확장자 받을 수 있게 하면 어떨지?

2022-03-18 14:44 UTC, yunyezl commented on Noonbody/Noonbody/Source/Presentation/Panorama/ViewControllers/PanoramaViewController.swift
> +    var bodyPart = "whole"
살짞 거슬린다(좀만이)

2022-03-20 08:05 UTC, yunyezl commented on Noonbody/Noonbody/Source/Presentation/Panorama/ViewModels/PanoramaViewModel.swift
> +import RealmSwift
요기서 Realm을 import 할 필요 없지 않나요?

2022-03-20 08:05 UTC, yunyezl commented on Noonbody/Noonbody/Source/Presentation/Panorama/Cells/BottomCollectionViewCell.swift
> +    func setCell(albumId: Int, bodyPart: String, imageName: Int, index: Int, fileExtension: String) {
이 부분에서 타입을 enum 타입 자체로 받아도 "\(FileExtension.png)" 으로 출력하면 그대로 사용할 수 있으니까
enum받는 건 어떨까요??

2022-03-20 08:05 UTC, yunyezl commented on Noonbody/Noonbody/Source/Presentation/Panorama/Cells/TopCollectionViewCell.swift
> +    func setPhotoCell(albumId: Int, bodyPart: String, imageName: Int, contentMode: Bool, fileExtension: String) {
setCell 함수랑, setPhotoCell 함수 파라미터가 둘 다 너무 많은 느낌이고 Path를 만드는 과정이 중복되는 것 같은데
Cell에 기존처럼 서버에서 제공하는 URL 넘기듯이 Directory Path를 파라미터로 넘기고,
별도로 해당 Path를 만드는 함수를 만들어서 setCell / setPhotoCell을 호출하기 전에 Path를 만들고 그 걸 넘겨주는 건 어떨까요?
(Path는 ViewModel에서 만들어서 넘겨주는 게 더 좋을 것 같긴 함)

2022-03-22 09:50 UTC, yunyezl approved these changes

2022-03-22 09:51 UTC, merged